# Generated by Django 4.0.2 on 2022-02-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_assignment_posted_date_assignment_total_marks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='score',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='total_marks',
        ),
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignmentstatus',
            name='status',
            field=models.BooleanField(choices=[(True, 'YES'), (False, 'Incomplete')], default=False),
        ),
    ]
