# Generated by Django 4.0.2 on 2022-02-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_assignment_deadline_remove_assignment_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentstatus',
            name='status',
            field=models.BooleanField(choices=[(True, 'Completed'), (False, 'Incomplete')], default=False),
        ),
    ]
