# Generated by Django 4.0.2 on 2022-02-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_assignment_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='user_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assignmentstatus',
            name='user_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='user_code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
