# Generated by Django 4.0.2 on 2022-02-24 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_assignment_user_code_assignmentstatus_user_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='user_code',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='user_code',
        ),
    ]
