# Generated by Django 4.0.2 on 2022-03-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_assignment_user_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='unique_code',
            field=models.CharField(default='random_id', editable=False, max_length=32),
        ),
    ]
