# Generated by Django 4.0.2 on 2022-03-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_classroom_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='unique_code',
            field=models.CharField(default='random_id', editable=False, max_length=7),
        ),
    ]
