# Generated by Django 4.0.2 on 2022-03-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_sandwich_sauce_saucequantity_remove_task_assignee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['headline'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.RemoveField(
            model_name='saucequantity',
            name='sandwich',
        ),
        migrations.RemoveField(
            model_name='saucequantity',
            name='sauce',
        ),
        migrations.DeleteModel(
            name='Sandwich',
        ),
        migrations.DeleteModel(
            name='Sauce',
        ),
        migrations.DeleteModel(
            name='SauceQuantity',
        ),
        migrations.AddField(
            model_name='article',
            name='publications',
            field=models.ManyToManyField(to='api.Publication'),
        ),
    ]
