# Generated by Django 4.0.2 on 2022-03-15 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0019_article_publication_remove_saucequantity_sandwich_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='title',
            field=models.CharField(default='Classroom Name', max_length=30),
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='Member',
        ),
        migrations.AddField(
            model_name='classroom',
            name='Member',
            field=models.ManyToManyField(related_name='member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
