# Generated by Django 4.0.2 on 2022-03-15 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_classroom_title_remove_classroom_member_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='title',
            new_name='classroomName',
        ),
    ]
