# Generated by Django 4.0.3 on 2022-03-19 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_classroom_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='classroomName',
            new_name='className',
        ),
        migrations.RemoveField(
            model_name='assignmentstatus',
            name='user_code',
        ),
    ]
