# Generated by Django 4.0.3 on 2022-03-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_classroomname_classroom_classname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='className',
            new_name='classroomName',
        ),
    ]
