# Generated by Django 4.0.3 on 2022-03-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_classname_classroom_classroomname'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='classCode',
            field=models.CharField(default='Classroom Code', max_length=6, unique=True),
        ),
    ]
