# Generated by Django 4.0.3 on 2022-03-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_classroom_classcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='classCode',
            field=models.CharField(max_length=6),
        ),
    ]
