# Generated by Django 4.0.2 on 2022-03-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_classroom_classcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='choice1',
            field=models.TextField(default='choice1', max_length=255),
        ),
        migrations.AddField(
            model_name='assignment',
            name='choice2',
            field=models.TextField(default='choice2', max_length=255),
        ),
    ]
