# Generated by Django 4.0.2 on 2022-03-20 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_assignment_choice1_assignment_choice2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='choice2',
            new_name='choice_false',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='choice1',
            new_name='choice_true',
        ),
    ]
