# Generated by Django 4.0.2 on 2022-03-23 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date_created',
        ),
    ]
