# Generated by Django 4.0.3 on 2022-03-25 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0034_alter_score_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FalseStudent', models.ManyToManyField(related_name='FalseStudent', to=settings.AUTH_USER_MODEL)),
                ('TrueStudent', models.ManyToManyField(related_name='TrueStudent', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='api.assignment')),
            ],
        ),
    ]
