# Generated by Django 4.0.3 on 2022-03-26 01:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0035_assignmentresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentresult',
            name='FalseStudent',
            field=models.ManyToManyField(null=True, related_name='FalseStudent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignmentresult',
            name='TrueStudent',
            field=models.ManyToManyField(null=True, related_name='TrueStudent', to=settings.AUTH_USER_MODEL),
        ),
    ]
