# Generated by Django 4.0.3 on 2022-03-28 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0036_alter_assignmentresult_falsestudent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentresult',
            name='FalseStudent',
            field=models.ManyToManyField(related_name='FalseStudent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignmentresult',
            name='TrueStudent',
            field=models.ManyToManyField(related_name='TrueStudent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='classCode',
            field=models.CharField(default='CODE', max_length=6),
        ),
    ]
